services:

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  toxiproxy:
    container_name: toxiproxy
    image: ghcr.io/shopify/toxiproxy
    command:
      - -host=0.0.0.0
      - -proxy-metrics
      - -config=/config/toxiproxy.json
    volumes:
      - ./toxiproxy/toxiproxy.json:/config/toxiproxy.json
    ports:
      - "8474:8474"
      - "8080:8080"
      - "8081:8081"

  toxiproxy-configurer:
    container_name: toxiproxy-configurer
    build:
      context: ./toxiproxy
      dockerfile: ./Dockerfile
    depends_on:
      toxiproxy:
        condition: service_started

  wiremock_a:
    container_name: wiremock_a
    image: wiremock/wiremock
    volumes:
      - ./wiremock/mappings/hello:/home/wiremock/mappings

  wiremock_b:
    container_name: wiremock_b
    image: wiremock/wiremock
    command: "--port 8081"
    volumes:
      - ./wiremock/mappings/goodbye:/home/wiremock/mappings

