services:

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  toxiproxy:
    container_name: toxiproxy
    image: ghcr.io/shopify/toxiproxy
    command:
      - -host=0.0.0.0
      - -proxy-metrics
      - -config=/config/toxiproxy.json
    volumes:
      - ./toxiproxy/toxiproxy.json:/config/toxiproxy.json
    ports:
      - "8474:8474"
      - "8080:8080"
      - "8081:8080"

  toxiproxy-configurator:
    container_name: toxiproxy-configurator
    build:
      context: ./toxiproxy
      dockerfile: ./Dockerfile
    depends_on:
      toxiproxy:
        condition: service_started

  wiremock:
    container_name: wiremock
    image: wiremock/wiremock
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
